### ISSUE TITLE
TODO:

### ISSUE THREAD

**Issue by zktuong** [zktuong/dandelion#1]
**Pre-processing**
~~- [ ] Do we run reassign_genotype for IGL/IGK and/or the J genes?~~ No.
- [x] Add in a step to rename the locus for multiple IGHV/J chain calls as ‘Multi’-whatever. Maybe after reassign_alleles
- [x] shift create_germlines to preprocessing?
- [x] retrieve identity score and length of constant region after assign_isotype
- - [x] also return the constant region sequence call to allow for manual checks and adjustments?
- [x] create a new column where constant genes are collapsed to isotypes

**Visualization and analysis**
- [x] Tabulate V/J gene usage – should be fairly straight forward
- - [x] Add an option to not sort the genes.
- - [x] Add a plotting function to plot this as a barplot
- - - [ ] and heatmap
- [x] Calculate mutation load
- - [x] Add a wrapper to shazam's basic mutational load R function
~~- - [ ] Add a plotting function to add this as a barplot, heatmap and/or violin plot~~ 
This can be achieve using scanpy's plotting modules
- - [ ] add in a step to 'fix' the V/J gene usage for clones. Need to figure out how to run this without breaking the function.
- - [x] Enable option to return the results of light chain and heavy chain mutations separately.
- - [ ] Add a wrapper to call IGoR?
- - [ ] or are there other methods?
- [x] Add a spectratype plots to show distribution of CDR3 junction lengths

**Finding clones**
- [x] Add in a wrapper to call Changeo’s DefineClones.py as an alternative way to call clones.
- - [x] Not sure if its working yet?
- - [ ] Also port in SCOPer?
- [ ] Add a function using graph-based community detection to define sub-clones base on the eventual network
- - [ ] figure out a different way to calculate the BCR network/embedding using distance matrices from heavy, light and potential transcriptomics data

**Network stats**
- [x] measures to describe the overall clonal structure in a single sample, or per clone.
- - [x] Calculate gini indices (e.g. size of clones versus number of clones)
- - [ ] node connectivity (network stability)
- - - [x] closeness-centrality ~~and betweeness-centrality~~ (highlight clonally expanded nodes!)
- - [ ] edge-betweeness (mutation rate/relationship)
- [x] Add a random sampling function to calculate the above if needed to control for sample size.

**Miscellaneous**
- [ ] Add parsing function to convert the processed BCR changeo/airr tsv format back to a 10x-style format because there’s some tools like immunarch that can parse 10x format for their analyses and some of the tools included look quite cool.
- [ ] Add parsing function to convert processed TCR data changeo/airr tsv format back to a 10x-style format to integrate with scirpy
- [ ] Bulk integration

**Documentation**
- [x] Update the documentation for the functions to ensure that they are descriptive enough for general use.
- [x] Add expected type of parameter into functions so it's a bit clearer for some of the more complicated ones. - added https://github.com/zktuong/dandelion/commit/533451251b3c2d177ecbdc6251acde42afd710d2
- [x] Clean up some spaghetti code in _tools.py and _plotting.py
- [x] update notebook 1 with reccomendations to stick to airr format
